import pygame
import random
import sys

# Colours
black = (0, 0, 0)
white = (255, 255, 255)
red = (255, 0, 0)
green = (0, 255, 0)
blue = (0, 0, 255)

pygame.font.init()
font = pygame.font.Font(pygame.font.get_default_font(), 30)
def main():

	FPS = 60

	maxHealth = 600
	currHealth = 600

	"""Player Stats"""
	#import from player class generated by the main menu, shop purchases
	Health = 20
	Speed = 5
	Gun = 10
	Knife = 5


	"""Stop timer conditions"""
	alive = True
	boss = True
	pause = False
	quit = False

	x=20
	y=275
	w=30
	h=30
	g=1
	r=2.5
	v=0
	s=Speed

	while not quit:

		pygame.init()
		screen=pygame.display.set_mode((800,600))
		pygame.display.set_caption("Game")

		pygame.time.delay(50)
		stop_condition = None

		for event in pygame.event.get():
			if event.type==pygame.QUIT:
				stop_condition = "quit"
				quit = True

		keys = pygame.key.get_pressed()

		if keys[pygame.K_LEFT]:
			x -= s
		if keys[pygame.K_RIGHT]:
			x += s
		if keys[pygame.K_DOWN]:
			v -= r
		v += g

		y -= v


		if keys[pygame.K_q]:
			currHealth -= Gun


		if x < 0 or x > 770 or y < 50 or y > 570:
			stop_condition = "dead"
			alive = False
			quit = True
			#death screen here
			pygame.QUIT()

		textsurface = font.render('%d / %d' %(currHealth, maxHealth), True, (120,120,200))

		screen.fill(black)

		pygame.draw.rect(screen, red, (0,0,800,50))
		pygame.draw.rect(screen, green, (0,0,currHealth/maxHealth*800,50))
		pygame.draw.rect(screen, blue, (x, y, w, h))
		screen.blit(textsurface,(350,0))

		pygame.display.update()


	return stop_condition




if __name__ == '__main__':
	main()